version: "2"
services:
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.envs/.flask
    volumes:
      - ./backend:/backend-app
    
  database:
    image: mysql:8.0.39
    ports:
      - "3200:3306"
    env_file:
      - ./database/.envs/.mysql
    volumes:
      - ./database/mysql_data:/var/lib/mysql

